/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/demo/': RouteRecordInfo<'/demo/', '/demo', Record<never, never>, Record<never, never>>,
    '/homepage/': RouteRecordInfo<'/homepage/', '/homepage', Record<never, never>, Record<never, never>>,
    '/homepage/Banner': RouteRecordInfo<'/homepage/Banner', '/homepage/Banner', Record<never, never>, Record<never, never>>,
    '/homepage/Footer': RouteRecordInfo<'/homepage/Footer', '/homepage/Footer', Record<never, never>, Record<never, never>>,
    '/homepage/ProductDisplay': RouteRecordInfo<'/homepage/ProductDisplay', '/homepage/ProductDisplay', Record<never, never>, Record<never, never>>,
    '/intro/': RouteRecordInfo<'/intro/', '/intro', Record<never, never>, Record<never, never>>,
    '/intro/components/Background': RouteRecordInfo<'/intro/components/Background', '/intro/components/Background', Record<never, never>, Record<never, never>>,
    '/intro/components/EnterButton': RouteRecordInfo<'/intro/components/EnterButton', '/intro/components/EnterButton', Record<never, never>, Record<never, never>>,
    '/intro/components/Header': RouteRecordInfo<'/intro/components/Header', '/intro/components/Header', Record<never, never>, Record<never, never>>,
    '/intro/components/ProjectInfo': RouteRecordInfo<'/intro/components/ProjectInfo', '/intro/components/ProjectInfo', Record<never, never>, Record<never, never>>,
    '/intro/components/TechStack': RouteRecordInfo<'/intro/components/TechStack', '/intro/components/TechStack', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
